# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pychat_pb2 as pychat__pb2


class ChatAPIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.login = channel.unary_unary(
        '/com.obytech.pychat.web.grpc.pychat_pb2.ChatAPI/login',
        request_serializer=pychat__pb2.LoginRequest.SerializeToString,
        response_deserializer=pychat__pb2.LoginResponse.FromString,
        )
    self.sendMessage = channel.unary_unary(
        '/com.obytech.pychat.web.grpc.pychat_pb2.ChatAPI/sendMessage',
        request_serializer=pychat__pb2.Msg.SerializeToString,
        response_deserializer=pychat__pb2.SendMessageResponse.FromString,
        )
    self.streamMessages = channel.unary_stream(
        '/com.obytech.pychat.web.grpc.pychat_pb2.ChatAPI/streamMessages',
        request_serializer=pychat__pb2.StreamMessagesRequest.SerializeToString,
        response_deserializer=pychat__pb2.Msg.FromString,
        )


class ChatAPIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def streamMessages(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatAPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'login': grpc.unary_unary_rpc_method_handler(
          servicer.login,
          request_deserializer=pychat__pb2.LoginRequest.FromString,
          response_serializer=pychat__pb2.LoginResponse.SerializeToString,
      ),
      'sendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.sendMessage,
          request_deserializer=pychat__pb2.Msg.FromString,
          response_serializer=pychat__pb2.SendMessageResponse.SerializeToString,
      ),
      'streamMessages': grpc.unary_stream_rpc_method_handler(
          servicer.streamMessages,
          request_deserializer=pychat__pb2.StreamMessagesRequest.FromString,
          response_serializer=pychat__pb2.Msg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.obytech.pychat.web.grpc.pychat_pb2.ChatAPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class SayHelloStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.send = channel.unary_unary(
        '/com.obytech.pychat.web.grpc.pychat_pb2.SayHello/send',
        request_serializer=pychat__pb2.Hello.SerializeToString,
        response_deserializer=pychat__pb2.HelloResponse.FromString,
        )


class SayHelloServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SayHelloServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'send': grpc.unary_unary_rpc_method_handler(
          servicer.send,
          request_deserializer=pychat__pb2.Hello.FromString,
          response_serializer=pychat__pb2.HelloResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.obytech.pychat.web.grpc.pychat_pb2.SayHello', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
