# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pychat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pychat.proto',
  package='com.obytech.pychat.web.grpc.pychat_pb2',
  syntax='proto3',
  serialized_pb=_b('\n\x0cpychat.proto\x12&com.obytech.pychat.web.grpc.pychat_pb2\"&\n\x15StreamMessagesRequest\x12\r\n\x05token\x18\x01 \x01(\t\" \n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"c\n\rLoginResponse\x12\x43\n\x06status\x18\x01 \x01(\x0e\x32\x33.com.obytech.pychat.web.grpc.pychat_pb2.LoginStatus\x12\r\n\x05token\x18\x02 \x01(\t\"+\n\x03Msg\x12\x13\n\x0b\x64\x65stination\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"U\n\x13SendMessageResponse\x12>\n\x06status\x18\x01 \x01(\x0e\x32..com.obytech.pychat.web.grpc.pychat_pb2.Status\"\"\n\x05Hello\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1c\n\rHelloResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t*6\n\x0bLoginStatus\x12\x0b\n\x07SUCCEED\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0e\n\nLOGGED_OUT\x10\x02*3\n\x06Status\x12\x0f\n\x0bON_DELIVERY\x10\x00\x12\r\n\tDELIVERED\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x32\xff\x02\n\x07\x43hatAPI\x12v\n\x05login\x12\x34.com.obytech.pychat.web.grpc.pychat_pb2.LoginRequest\x1a\x35.com.obytech.pychat.web.grpc.pychat_pb2.LoginResponse\"\x00\x12y\n\x0bsendMessage\x12+.com.obytech.pychat.web.grpc.pychat_pb2.Msg\x1a;.com.obytech.pychat.web.grpc.pychat_pb2.SendMessageResponse\"\x00\x12\x80\x01\n\x0estreamMessages\x12=.com.obytech.pychat.web.grpc.pychat_pb2.StreamMessagesRequest\x1a+.com.obytech.pychat.web.grpc.pychat_pb2.Msg\"\x00\x30\x01\x32z\n\x08SayHello\x12n\n\x04send\x12-.com.obytech.pychat.web.grpc.pychat_pb2.Hello\x1a\x35.com.obytech.pychat.web.grpc.pychat_pb2.HelloResponse\"\x00\x62\x06proto3')
)

_LOGINSTATUS = _descriptor.EnumDescriptor(
  name='LoginStatus',
  full_name='com.obytech.pychat.web.grpc.pychat_pb2.LoginStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCEED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGGED_OUT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=429,
  serialized_end=483,
)
_sym_db.RegisterEnumDescriptor(_LOGINSTATUS)

LoginStatus = enum_type_wrapper.EnumTypeWrapper(_LOGINSTATUS)
_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='com.obytech.pychat.web.grpc.pychat_pb2.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ON_DELIVERY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELIVERED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=485,
  serialized_end=536,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
SUCCEED = 0
FAILED = 1
LOGGED_OUT = 2
ON_DELIVERY = 0
DELIVERED = 1
ERROR = 2



_STREAMMESSAGESREQUEST = _descriptor.Descriptor(
  name='StreamMessagesRequest',
  full_name='com.obytech.pychat.web.grpc.pychat_pb2.StreamMessagesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='com.obytech.pychat.web.grpc.pychat_pb2.StreamMessagesRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=94,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='com.obytech.pychat.web.grpc.pychat_pb2.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='com.obytech.pychat.web.grpc.pychat_pb2.LoginRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=128,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='com.obytech.pychat.web.grpc.pychat_pb2.LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='com.obytech.pychat.web.grpc.pychat_pb2.LoginResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='com.obytech.pychat.web.grpc.pychat_pb2.LoginResponse.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=229,
)


_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='com.obytech.pychat.web.grpc.pychat_pb2.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='destination', full_name='com.obytech.pychat.web.grpc.pychat_pb2.Msg.destination', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='com.obytech.pychat.web.grpc.pychat_pb2.Msg.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=274,
)


_SENDMESSAGERESPONSE = _descriptor.Descriptor(
  name='SendMessageResponse',
  full_name='com.obytech.pychat.web.grpc.pychat_pb2.SendMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='com.obytech.pychat.web.grpc.pychat_pb2.SendMessageResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=361,
)


_HELLO = _descriptor.Descriptor(
  name='Hello',
  full_name='com.obytech.pychat.web.grpc.pychat_pb2.Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.obytech.pychat.web.grpc.pychat_pb2.Hello.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='com.obytech.pychat.web.grpc.pychat_pb2.Hello.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=397,
)


_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='com.obytech.pychat.web.grpc.pychat_pb2.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='com.obytech.pychat.web.grpc.pychat_pb2.HelloResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=427,
)

_LOGINRESPONSE.fields_by_name['status'].enum_type = _LOGINSTATUS
_SENDMESSAGERESPONSE.fields_by_name['status'].enum_type = _STATUS
DESCRIPTOR.message_types_by_name['StreamMessagesRequest'] = _STREAMMESSAGESREQUEST
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.message_types_by_name['SendMessageResponse'] = _SENDMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['Hello'] = _HELLO
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE
DESCRIPTOR.enum_types_by_name['LoginStatus'] = _LOGINSTATUS
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamMessagesRequest = _reflection.GeneratedProtocolMessageType('StreamMessagesRequest', (_message.Message,), dict(
  DESCRIPTOR = _STREAMMESSAGESREQUEST,
  __module__ = 'pychat_pb2'
  # @@protoc_insertion_point(class_scope:com.obytech.pychat.web.grpc.pychat_pb2.StreamMessagesRequest)
  ))
_sym_db.RegisterMessage(StreamMessagesRequest)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'pychat_pb2'
  # @@protoc_insertion_point(class_scope:com.obytech.pychat.web.grpc.pychat_pb2.LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRESPONSE,
  __module__ = 'pychat_pb2'
  # @@protoc_insertion_point(class_scope:com.obytech.pychat.web.grpc.pychat_pb2.LoginResponse)
  ))
_sym_db.RegisterMessage(LoginResponse)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), dict(
  DESCRIPTOR = _MSG,
  __module__ = 'pychat_pb2'
  # @@protoc_insertion_point(class_scope:com.obytech.pychat.web.grpc.pychat_pb2.Msg)
  ))
_sym_db.RegisterMessage(Msg)

SendMessageResponse = _reflection.GeneratedProtocolMessageType('SendMessageResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDMESSAGERESPONSE,
  __module__ = 'pychat_pb2'
  # @@protoc_insertion_point(class_scope:com.obytech.pychat.web.grpc.pychat_pb2.SendMessageResponse)
  ))
_sym_db.RegisterMessage(SendMessageResponse)

Hello = _reflection.GeneratedProtocolMessageType('Hello', (_message.Message,), dict(
  DESCRIPTOR = _HELLO,
  __module__ = 'pychat_pb2'
  # @@protoc_insertion_point(class_scope:com.obytech.pychat.web.grpc.pychat_pb2.Hello)
  ))
_sym_db.RegisterMessage(Hello)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), dict(
  DESCRIPTOR = _HELLORESPONSE,
  __module__ = 'pychat_pb2'
  # @@protoc_insertion_point(class_scope:com.obytech.pychat.web.grpc.pychat_pb2.HelloResponse)
  ))
_sym_db.RegisterMessage(HelloResponse)



_CHATAPI = _descriptor.ServiceDescriptor(
  name='ChatAPI',
  full_name='com.obytech.pychat.web.grpc.pychat_pb2.ChatAPI',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=539,
  serialized_end=922,
  methods=[
  _descriptor.MethodDescriptor(
    name='login',
    full_name='com.obytech.pychat.web.grpc.pychat_pb2.ChatAPI.login',
    index=0,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_LOGINRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='com.obytech.pychat.web.grpc.pychat_pb2.ChatAPI.sendMessage',
    index=1,
    containing_service=None,
    input_type=_MSG,
    output_type=_SENDMESSAGERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='streamMessages',
    full_name='com.obytech.pychat.web.grpc.pychat_pb2.ChatAPI.streamMessages',
    index=2,
    containing_service=None,
    input_type=_STREAMMESSAGESREQUEST,
    output_type=_MSG,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATAPI)

DESCRIPTOR.services_by_name['ChatAPI'] = _CHATAPI


_SAYHELLO = _descriptor.ServiceDescriptor(
  name='SayHello',
  full_name='com.obytech.pychat.web.grpc.pychat_pb2.SayHello',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=924,
  serialized_end=1046,
  methods=[
  _descriptor.MethodDescriptor(
    name='send',
    full_name='com.obytech.pychat.web.grpc.pychat_pb2.SayHello.send',
    index=0,
    containing_service=None,
    input_type=_HELLO,
    output_type=_HELLORESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAYHELLO)

DESCRIPTOR.services_by_name['SayHello'] = _SAYHELLO

# @@protoc_insertion_point(module_scope)
